### ISSUE TITLE
Flag for "datdaemon add" to not complain if a hash already exists

### ISSUE THREAD

**Issue by mitar** [soyuka/dat-daemon#12]
Currently it dies, which makes it hard to script (because i would like to differentiate between already added and other errors).

**Comment by soyuka** [comment]
https://github.com/soyuka/dat-daemon/blob/master/index.js#L48

Need to test this :|. Thanks for the report.

**Comment by soyuka** [comment]
Wait in fact you should be able to test this just fine, it exits with a code `1`, would another code do the trick?

**Comment by mitar** [comment]
Does it always exit with 1 only if the key is already added? No other cause makes it exist with 1?

So I imagine something like `rm -f` flag, which makes `rm` exist with 0. So then I would not even have to check the return code value. (And generally it is hard to assure that the return code is not reused because some other library might exit with 1 for example for some other reason.)

**Comment by soyuka** [comment]
Exits with code 2 in this case :).

**Comment by mitar** [comment]
Thanks!
